Chore: add outputs nlb dns
camptocamp/devops-stack-module-cluster-eks pull request #29
Opened 2024-08-22 09:17 UTC by lconsuegra

## Description of the changes

In order to be able to create alias records pointing to AWS resources we need the dns name and zone_id of the Netwok Load Balancers.

Tested locally with :

```
resource "aws_route53_record" "app2" {
  zone_id = data.aws_route53_zone.this.zone_id

  name = "app2"
  type = "A"

  alias {
    name                   = module.cluster_red.nlb_dns_name["public"]
    zone_id                = module.cluster_red.nlb_zone_id["public"]
    evaluate_target_health = true
  }
}
```

Ps: I also changed the description for nlb_target_group after I tried to user it to have the NLB ARNs like it said..

## Breaking change

- [X] No
- [ ] Yes

2024-08-22 10:18 UTC, lentidas requested changes
LGTM. I've just made a few suggestions to the descriptions of the variables.

Other than that, I would just change the scope of the PR from `chore` to `feat` (since this adds a new output to the module) in order to trigger a new release. If you do this, you need to do a _Squash and merge_. If you do a _Rebase and merge_ you need to reword you commit messages instead :wink:

2024-08-22 10:18 UTC, lentidas commented on outputs.tf
> +  description = "Map of the DNS name of the load balancer (public and/or private if enabled)."
```suggestion
  description = "Map of the DNS names of the load balancers (public and/or private if enabled). Returns `null` if the respective load balancer is disabled."
```

2024-08-22 10:18 UTC, lentidas commented on outputs.tf
> +  description = "Map of the zone_id of the load balancer to assist with creating DNS records (public and/or private if enabled)."
```suggestion
  description = "Map of the zone_id of the load balancer to assist with creating DNS records (public and/or private if enabled). Returns `null` if the respective load balancer is disabled."
```

2024-08-23 06:17 UTC, lconsuegra commented
Thanks for the review Gonçalo, I have rewrited my commit with your suggestions
You need to approve again, and you can merge if its all good or I will.

Ragards.

2024-08-27 15:44 UTC, lentidas approved these changes

2024-08-27 15:45 UTC, merged